config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check
  if Rails.env.development?
    get "/scrape", to:"scraper#index"
  end

  resources :products, only: [:index, :show]
  resource :filetered_products, only: [:show]
  root "products#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
  def extract_price_and_currency(string)
    match = string.match(/(\D+)\s*([\d\s]+)/)
    if match
      currency = match[1].strip
      price = match[2].strip.gsub(/\s+/, '').to_i
      return price, currency
    else
      return nil, nil
    end


  end
end

app/models/price_record.rb
class PriceRecord < ApplicationRecord
    belongs_to :product

    # Checks if products does exist too
    validates_associated :product

    # Checks if products does exist too
    validates_presence_of :price
    validates_presence_of :date

end

app/models/product.rb
class Product < ApplicationRecord
    validates_presence_of :name
    validates_presence_of :image
    has_many :price_records, dependent: :destroy
    has_many :source_of_products, dependent: :destroy

    def searchVector(otherTerm)

        tfIdfVector=TextProcessing::TfIdfVector.new()
        tfIdfVector=tfIdfVector.vectorForSearch(name, otherTerm)

        return tfIdfVector
    end

    def saveProductSource(price, image, link, batch_id)
        priceNumerical, currency = extract_price_and_currency(price)
        sourceOfProduct=SourceOfProduct.new(
            product_id: id, 
            name: name, 
            price: priceNumerical, 
            image: image, 
            link: link,
            currency: currency
        )
        sourceOfProduct.newPriceRecord(id, batch_id)
        sourceOfProduct.save

    end

    def price_change
        # How much the price have gotten up or down by %
        # ? Shouldn't be the smallest price change instead of average?

        return 0 unless price_records&.any?
      
        oldest_record = price_records.order(date: :asc).first
        old_price = oldest_record.price
      
        sum_price = price_records.sum(:price)
        average_price = sum_price.to_f / price_records.count
      
        return 0 if average_price.zero?
      
        price_difference = old_price - average_price
        difference_percentage = (price_difference / average_price) * 100
      
        difference_percentage.to_i
      end

    def find_smallest_price
        # Getting the smallest price if any price records
        return 0 unless price_records&.any?
        price_records.sort_by {|price_record| price_record.price}[0].price
    end

end

app/models/product_source.rb
class ProductSource < ApplicationRecord
end

app/models/scrape_record.rb
class ScrapeRecord < ApplicationRecord
end

app/models/source_of_product.rb
class SourceOfProduct < ApplicationRecord
  belongs_to :product
  validates_associated :product

  def newPriceRecord(product_id, batch_id)
    PriceRecord.new(
      product_id:product_id, 
      price: price, 
      date:Date.today, 
      currency: currency,
      batch: batch_id
    ).save
  end
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
  
    validates :name, presence: true, uniqueness: true
    validates :password, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :currentUser

    def currentUser
      @currentUser ||= User.find_by(id: session[:user_id]) if session[:user_id]
    end

    
  def redirectLoggedInUser
    if currentUser
      redirect_to root_path 
    end
  end
end

app/controllers/home_controller.rb
require_relative 'textProcessing/tfIdf'

class HomeController < ApplicationController

    def index
        @products=Product.all
        render "home"
    end

    def show
        productId=params[:id]
        @product=Product.find(productId)
        @priceRecords=PriceRecord.where(productId: productId).pluck(:price, :date)

        @productSource=SourceOfProduct.where(productId:productId)

    end


end

app/controllers/notification_controller.rb
class NotificationController < ApplicationController
end

app/controllers/products_controller.rb
require_relative 'textProcessing/tfIdf'
# ? Wtf er tfIDf?
class ProductsController < ApplicationController
    def index
        @products=Product.all
    end

    def show
        product_id=params[:id]
        @product=Product.find(product_id)
        # Have to have date and price for chart
        @price_records = @product.price_records.pluck(:date,:price)

        @product_source=@product.source_of_products

    end


end

app/controllers/scraper_controller.rb
require_relative '../services/scrapers'

class ScraperController < ApplicationController
    include ScraperHelper
    def index
        # separating search_terms by ","
        search_terms = params[:search_terms]&.split(",")

        # Defaults to air jordan 1
        if not search_terms.present? or search_terms.empty?
          search_terms = ["air jordan 1"]
        end

        ScrapersService.new.call(search_terms: search_terms)

        # TODO: Get amount of products and pricerecords made and show them?
        render json:{status:"200 success", searching_terms: search_terms}
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/category_page_helper.rb
module CategoryPageHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/notification_helper.rb
module NotificationHelper
end

app/helpers/scraper_helper.rb
require 'nokogiri'
require 'open-uri'

module ScraperHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/signup_helper.rb
module SignupHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrisJakt</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="csrf-token" content="<%= form_authenticity_token %>">

    <%= stylesheet_link_tag "home/product" %>
    <%= stylesheet_link_tag "home/header" %>
    <%= stylesheet_link_tag "home/details" %>
    <%= stylesheet_link_tag "home/search" %>
    <%= stylesheet_link_tag "home/style" %>

    <%= stylesheet_link_tag "filter_page/style" %>

    <%= stylesheet_link_tag "style" %>


    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "layouts/nav/menu" %>
    <main>
      <%= yield %>
    </main>


    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

app/views/layouts/nav/_category.html.erb
<!--* Can use keyboard to choose sub category -->
<!--! Can't use keyboard to choose category -->

<div class="category" data-controller="dropdown" data-action="focusout->dropdown#hideContent">
  <button data-action="click->dropdown#showContent "><%= name %></button>

  <div hidden data-dropdown-target="content" class="sub-categories">
    <% sub_categories.each do |name| %>
      <%= render "layouts/nav/sub_category", name: name %>
    <% end %>
  </div>

</div>

app/views/layouts/nav/_menu.html.erb
<header>
  <div class="header">
    <div class="headerContainerTop headerContainer">
      <a href="<%= root_path%>">
        [logo here]
      </a>

    </div>
    <div class="headerContainerBottom headerContainer">
      <div class="categories">
        <%= render "layouts/nav/category", name: "Electronics", sub_categories: ["1", "2"] %>
        <%= render "layouts/nav/category", name: "Clothes" , sub_categories: ["1", "2"]%>
        <%= render "layouts/nav/category", name: "Home" , sub_categories: ["1", "2"]%>
        <%= render "layouts/nav/category", name: "Garden" , sub_categories: ["1", "2"]%>
        <%= render "layouts/nav/category", name: "Car", sub_categories: ["Engine", "Parts"] %>
        <%= render "layouts/nav/category", name: "Sport & Hobby", sub_categories: ["Football", "American football"] %>
      </div>

      <!-- Search -->
      <div class="searchBarContainer">
        <%= form_with(url: filetered_products_path, method: "get", class: "searchBar") do %>
          <% request.query_parameters.each do |key, value| %>
            <%= hidden_field_tag key, value unless key.in?(['search']) %>
          <% end %>

          <button type="submit">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-search" viewBox="0 0 16 16">
              <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001q.044.06.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1 1 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0"/>
            </svg>
          </button>
          <%= text_field_tag :search, params[:search], placeholder: "Search" %>
        <% end %>

      </div>
      <% if Rails.env.development? %>
        <%= form_with(url: scrape_path, method: "get") do %>
          <%= text_field_tag :search_terms, params[:search_terms], placeholder: "search_terms" %>

          <button type="submit">scrape</button>

        <% end %>
      <% end %>

        <!-- Logout and login-->
        <% if user_signed_in? %>
          Logged in as: <%= current_user.email %>
          <%= link_to "Logout", destroy_user_session_path, data: { turbo_method: :delete } %>
        <% else %>
          <%= link_to "Login", new_user_session_path %>
        <% end %>

    </div>


  </div>
</header>

app/views/layouts/nav/_sub_category.html.erb
<!-- TODO onclick take to category -->
<button><%= name %></button>